name: Main workflow
on: push

jobs:
  test:
    name: Test Suite
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, macOS-latest, windows-latest ]
        rust: [ stable ]
    steps:
      - name: Setup | Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup | Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: ${{ matrix.rust }}
          profile: minimal
          override: true
          
      - name: Build | Test
        run: cargo test